Задание 3. Создан "скелет" бота
gpb-it-factory/gluharyov-telegram-bot pull request #5
Opened 2024-05-20 09:26 UTC by CoreXYZ1

2024-05-20 09:54 UTC, konstantin-kozlovskiy requested changes
Необходимо исправить замечания

2024-05-20 09:54 UTC, konstantin-kozlovskiy commented on .idea/artifacts/gluharyov_telegram_bot_jar.xml
> +<component name="ArtifactManager">
вся папка .idea должна быть в .gitignore и не должна попадать в репу

2024-05-20 09:54 UTC, konstantin-kozlovskiy commented on HELP.md
> +# Read Me First
Зачем нужен этот файл?

2024-05-20 09:54 UTC, konstantin-kozlovskiy commented on README.md
> +## Установка клаccного минибанка
Следует избегать эпитетов в технической документации, убираем "классный"

2024-05-20 09:54 UTC, konstantin-kozlovskiy commented on build/libs/gluharyov-telegram-bot-0.0.1-SNAPSHOT.jar
папку build в .gitignore, не должно быть джарника в репе

2024-05-20 09:54 UTC, konstantin-kozlovskiy commented on src/main/java/com/minibank/gluharyovtelegrambot/service/NiceTeleBot.java
> +            log.error("При ответе возникла проблема");
что даст тебе такое сообщение? отсутствует стак трейс, ты никогда не поймешь в чем была проблема, добавь в log.error(message, e)

2024-05-21 09:00 UTC, CoreXYZ1 commented on .idea/artifacts/gluharyov_telegram_bot_jar.xml
> +<component name="ArtifactManager">
Добавил папку .idea в .gitignore

2024-05-21 09:01 UTC, CoreXYZ1 commented on README.md
> +## Установка клаccного минибанка
Поправил название везде в README

2024-05-21 09:07 UTC, CoreXYZ1 commented on build/libs/gluharyov-telegram-bot-0.0.1-SNAPSHOT.jar
Сделал

2024-05-21 09:08 UTC, CoreXYZ1 commented on src/main/java/com/minibank/gluharyovtelegrambot/service/NiceTeleBot.java
> +            log.error("При ответе возникла проблема");
Исправил на log.error(e.getMessage());

2024-05-21 09:27 UTC, CoreXYZ1 commented on HELP.md
> +# Read Me First
Файл удалил, он не нужен, автоматически создался.

2024-06-04 10:48 UTC, konstantin-kozlovskiy requested changes
ты добавил папки в .gitignore, но они не пропали из MR, они уже в индексе и запушены в твоем коммите. Убери из гитигнора, удали из гита файлы, закоммить, и потом снова добавь в гитигнор, таким несложным упражнением, добейся чтобы файлы пропали из МР

2024-06-04 10:48 UTC, konstantin-kozlovskiy commented on src/main/java/com/minibank/gluharyovtelegrambot/service/NiceTeleBot.java
> +            log.error(e.getMessage());
Ключевое изменение должно быть не в том , что мы добавляем e.getMessage(), а в том что вторым аргументом передадим в логгер exception. log.error("Проблема при отправке сообщения", e) - это напечатает в лог стактрейс

2024-06-04 10:48 UTC, konstantin-kozlovskiy commented on .idea/.gitignore
![image](https://github.com/gpb-it-factory/gluharyov-telegram-bot/assets/168074443/93d4576e-e6a6-4f29-8f0d-1e37e1bee6bb)
ты добавил папки в .gitignore, но они не пропали из MR, они уже в индексе и запушены в твоем коммите. Убери из гитигнора, удали из гита файлы, закоммить, и потом снова добавь в гитигнор, таким несложным упражнением, добейся чтобы файлы пропали из МР

2024-06-05 10:43 UTC, CoreXYZ1 commented on src/main/java/com/minibank/gluharyovtelegrambot/service/NiceTeleBot.java
> +            log.error(e.getMessage());
Исправил

2024-06-05 10:44 UTC, CoreXYZ1 commented on .idea/.gitignore
Исправил

2024-06-13 08:47 UTC, konstantin-kozlovskiy approved these changes

2024-06-13 08:47 UTC, merged